export const serviceQueryKeys = {
  TODO_GET_ALL: 'TODO_GET_ALL',
  TODO_CREATE: 'TODO_CREATE',
  TODO_DELETE: 'TODO_DELETE',
  TODO_COMPLETE: 'TODO_COMPLETE',
  TODO_UNCOMPLETE: 'TODO_UNCOMPLETE',
};
