export const serviceQueryKeys = {
  TODO_GET_ALL: 'TODO_GET_ALL',
  TODO_GET_ONE_BY_ID: 'TODO_GET_ONE_BY_ID',
  TODO_CREATE: 'TODO_CREATE',
  TODO_DELETE: 'TODO_DELETE',
  TODO_COMPLETE: 'TODO_COMPLETE',
  TODO_UNCOMPLETE: 'TODO_UNCOMPLETE',
  TODO_FAVORITE: 'TODO_FAVORITE',
  TODO_UNFAVORITE: 'TODO_UNFAVORITE',
};
