export const networkQueryKeys = {
  GET_TODO_LIST: 'GET_TODO_LIST',
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  UNCOMPLETE_TODO: 'UNCOMPLETE_TODO',
};
