export const networkQueryKeys = {
  GET_TODO_LIST: 'GET_TODO_LIST',
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  UNCOMPLETE_TODO: 'UNCOMPLETE_TODO',
  GET_TODO: 'GET_TODO',
  GET_SAVED_FOR_LATER_TODO_LIST: 'GET_SAVED_FOR_LATER_TODO_LIST',
  GET_SAVED_FOR_LATER_TODO: 'GET_SAVED_FOR_LATER_TODO',
  SAVE_FOR_LATER: 'SAVE_FOR_LATER',
  DELETE_SAVED_FOR_LATER_TODO: 'DELETE_SAVED_FOR_LATER_TODO',
};
